import { NextResponse } from 'next/server';

/**
 * GET /api/firebase-sw-config
 *
 * Returns a tiny JS snippet that sets the Firebase public config
 * as global variables on the service worker's self scope.
 *
 * The service worker imports this URL via importScripts() so it can
 * initialize Firebase without bundling env vars into a static file.
 */
export async function GET() {
  const js = `
// Auto-generated by /api/firebase-sw-config — do not edit manually.
// This file injects the public Firebase config into the Service Worker scope.
self.FIREBASE_API_KEY             = ${JSON.stringify(process.env.NEXT_PUBLIC_FIREBASE_API_KEY || '')};
self.FIREBASE_AUTH_DOMAIN         = ${JSON.stringify(process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN || '')};
self.FIREBASE_PROJECT_ID          = ${JSON.stringify(process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID || '')};
self.FIREBASE_STORAGE_BUCKET      = ${JSON.stringify(process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET || '')};
self.FIREBASE_MESSAGING_SENDER_ID = ${JSON.stringify(process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID || '')};
self.FIREBASE_APP_ID              = ${JSON.stringify(process.env.NEXT_PUBLIC_FIREBASE_APP_ID || '')};
`.trim();

  return new NextResponse(js, {
    headers: {
      'Content-Type': 'application/javascript; charset=utf-8',
      // Cache for 1 hour — changes require a new SW registration anyway
      'Cache-Control': 'public, max-age=3600',
    },
  });
}
